### ISSUE TITLE
帮忙看下显示这个是怎么回事

### ISSUE THREAD

**Issue by sdshdv** [abbeyokgo/PyOne#100]
{"error":{"code":"serviceNotAvailable","message":"Service unavailable","retryAfterSeconds":30}} 

现在无论在pyone下载哪个文件都显示这个了，但是直接打开onedrive可以正常下载文件，是API请求超标了吗？有解决办法吗？

**Comment by MoeSakuraWorld** [comment]
同问

**Comment by abbeyokgo** [comment]
解决办法：等
