### ISSUE TITLE
[功能请求]定时更新列表

### ISSUE THREAD

**Issue by shzxm** [abbeyokgo/PyOne#108]
[功能请求]定时更新列表
![image](https://user-images.githubusercontent.com/9905297/62775157-7b406c80-bad9-11e9-97b7-69c18fee3c41.png)
不知道n能不能在这个地方添加一个定时更新功能.

**Comment by abbeyokgo** [comment]
设置个定时任务的事情。参考：https://www.showdoc.cc/pyone?page_id=2579534667126085
