### ISSUE TITLE
按步骤安装完毕，并设置了密码，但是admin页面登录不了

### ISSUE THREAD

**Issue by zuoakang** [abbeyokgo/PyOne#112]
登录后台界面输入密码后，页面没有反应，也不提示错误信息。

**Comment by abbeyokgo** [comment]
检查`self_config.py`里面的`password`是不是你设置的密码

**Comment by zuoakang** [comment]
@abbeyokgo  到redis重设密码好了，这是这样操作不友好，没有提示密码错误，只能手动到redis修改密码。。
