### ISSUE TITLE
若目錄非根目錄，會將檔案新增到根目錄下

### ISSUE THREAD

**Issue by Gdist** [abbeyokgo/PyOne#13]
例如設置目錄為/Folder1
若在/Folder1/Folder2下建立.password
實際上會將.password新增到/Folder2下

**Comment by abbeyokgo** [comment]
没有你说的这种情况。QQ群：864996565

**Comment by Gdist** [comment]
若A:對應分享目录 /Shared/Anime
則在後台對A:添加密碼保護
.password會出現在OneDrive之根目錄下

https://i.imgur.com/xCZp7Tb.png
https://i.imgur.com/UnikTG1.png

**Comment by abbeyokgo** [comment]
这个可以看看

**Comment by abbeyokgo** [comment]
@Gdist 已修复
