### ISSUE TITLE
那么问题来了，多个网盘怎么删除？

### ISSUE THREAD

**Issue by jmireles7** [abbeyokgo/PyOne#16]
第一次绑定，没成功，没看到哪里编辑的，多加了一个，成功了，然后悲剧了，第一个怎么删除？

**Comment by abbeyokgo** [comment]
看wiki：https://wiki.pyone.me

**Comment by jmireles7** [comment]
抱歉抱歉，之前在后台管理的章节拼命找，没想到在安装章节。
