### ISSUE TITLE
离线下载高CPU占用，及个人临时解决方式

### ISSUE THREAD

**Issue by ijglb** [abbeyokgo/PyOne#17]
经使用观察发现离线下载后如果没有及时清除任务，function.py将会长期驻留进程并进行死循环，导致极高的CPU占用率。
我自己尝试调整了function.py中download_and_upload函数，在完成后及时退出进程，目前使用正常，也不会出现高CPU占用的情况了。
相关代码调整：https://github.com/ijglb/PyOne/blob/8a2eec16040a7eb740ee3800c2b55deb9e61aefa/function.py#L1158-L1198

**Comment by abbeyokgo** [comment]
欢迎pr

**Comment by ijglb** [comment]
@abbeyokgo 我fork后的修改还带了一些私货，不好提交pr

**Comment by Rhilip** [comment]
git clone master分支，check出patch分支，把不夹带私货的提交到自己的库（git remote add），再pr不就行了吗？
