### ISSUE TITLE
能否考虑增加后台定时刷新文件目录的功能？

### ISSUE THREAD

**Issue by whka** [abbeyokgo/PyOne#22]
我是用别的方式上传文件到onedrive的，每次都需要手动刷新文件目录，能否考虑加个自动刷新的功能？

**Comment by weiyidu** [comment]
自己添加个定时任务吧

**Comment by whka** [comment]
将定时任务添加到crontab中会导致内存暴涨，不论间隔是2分钟、3分钟、5分钟、15分钟、1小时，内存都会从45%涨到94%+

**Comment by weiyidu** [comment]
> 将定时任务添加到crontab中会导致内存暴涨，不论间隔是2分钟、3分钟、5分钟、15分钟、1小时，内存都会从45%涨到94%+

哟西……

**Comment by zhuxiaole** [comment]
请问定时任务的刷新命令应该是啥？

**Comment by abbeyokgo** [comment]
@zhuxiaole https://wiki.pyone.me/pyone-ming-ling-hang-cao-zuo/geng-xin-huan-cun.html
另外不建议定时刷新，这将加大你的api被限制的可能
