### ISSUE TITLE
修改密码后无法登陆

### ISSUE THREAD

**Issue by powersee** [abbeyokgo/PyOne#29]
改了密码了，可以在 `config.py` 里面看到新的密码，但是后台一直无法登陆，使用 原本默认的 `PyOne` 也不行……

**Comment by abbeyokgo** [comment]
修改之后不会重启网站的话就重启服务器

**Comment by powersee** [comment]
> 修改之后不会重启网站的话就重启服务器

感谢，现在好了

**Comment by YooDing** [comment]
你新版本怎么修改后台密码？？页面写的什么花里胡哨的，真乱
