### ISSUE TITLE
如果不是分享的根目录，设置密码之类的文件创建会错误

### ISSUE THREAD

**Issue by amoshere** [abbeyokgo/PyOne#33]
比如我分享的是share这个文件夹，如果在后台对/share/a目录设置密码，
.password会创建在OneDrive的/a目录，而不是创建在/share/a目录下

**Comment by sdshdv** [comment]
我也遇到了同样的问题

**Comment by abbeyokgo** [comment]
这个之前就解决了，可以更新代码
