### ISSUE TITLE
打开TXT格式的文件会报500错误!

### ISSUE THREAD

**Issue by sdshdv** [abbeyokgo/PyOne#34]
用了几天什么都好,就是不能在线看TXT文档,也没法下载,会报500错误,具体提示如下:
Opps....500错误！
一般是因为服务器内部出现问题，可检查

Redis、MongoDB是否安装？是否运行？
如果上诉没问题，可清空Redis缓存：

redis-cli
 > FLUSHALL
如清空Redis缓存还有问题，可手动运行网站查看错误

supervisorctl -c supervisord.conf stop pyone && gunicorn -k eventlet -b 0:34567 run:app
然后再访问页面，查看ssh的错误提示

**Comment by abbeyokgo** [comment]
刷新你的缓存。没问题的。
