### ISSUE TITLE
配置出现错误

### ISSUE THREAD

**Issue by wehooshen** [abbeyokgo/PyOne#4]
配置完第一个页面点击“下一步”后出现错误
Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

**Comment by abbeyokgo** [comment]
自己确认：源码下的config.py的config_dir参数是不是当前的源码目录

**Comment by wehooshen** [comment]
设置了正确目录还是错误

**Comment by wehooshen** [comment]
> 自己确认：源码下的config.py的config_dir参数是不是当前的源码目录

设置了正确目录还是错误
