### ISSUE TITLE
关于修改绑定网盘数量上遇到的一点问题

### ISSUE THREAD

**Issue by aswww89** [abbeyokgo/PyOne#41]
想绑定四个  按照wiki上说的 以为在宝塔复制粘贴就行 但总出错
后发现一个细节大佬没有提醒
具体原因不懂 但是看大佬写的那三个盘符的代码 前两段代码最后}后边还加了一个,符号   但是最后一个没加
小白复制的时候就直接复制最后一个然后粘贴 成了最后两段代码}后都没有,这个符号了  结果就出错了  
建议大佬把这个细节优化下

**Comment by Rhilip** [comment]
学点基础

**Comment by abbeyokgo** [comment]
已经支持后台直接添加、删除网盘
