### ISSUE TITLE
在线播放时画质被压缩，无法选择画质

### ISSUE THREAD

**Issue by waahaa** [abbeyokgo/PyOne#42]
![1](https://user-images.githubusercontent.com/41323324/51097790-bd365800-1801-11e9-9589-778ac3f05fa1.png)

**Comment by lonepair** [comment]
不用DASH视频就好, 在设置里换一下

**Comment by waahaa** [comment]
> 不用DASH视频就好, 在设置里换一下

请问具体是在哪里设置？

**Comment by lonepair** [comment]
> > 不用DASH视频就好, 在设置里换一下
> 
> 请问具体是在哪里设置？

我已经不用了, 所以只记得大概是去后台找`显示设置`或者类似的栏目

**Comment by waahaa** [comment]
@lonepair 是不是记错了？PyOne后台并没有关于dash流视频相关的设置，OLAINDEX倒是有

**Comment by lonepair** [comment]
> @lonepair 是不是记错了？PyOne后台并没有关于dash流视频相关的设置，OLAINDEX倒是有

那是我记错了, oneindex和OLAINDEX都有的, 你可以@作者试试

**Comment by abbeyokgo** [comment]
dash无法选择清晰度，不用想了
