### ISSUE TITLE
关于后台中，"全量更新"按钮的bug

### ISSUE THREAD

**Issue by yk2008ok** [abbeyokgo/PyOne#50]
之前用debian9安装，来回折腾。。。
只要在网站后台一按全量更新，目录直接爆炸，后台密码立刻会被重置为默认密码。。
一开始以为是我安装错误，换了centos7后，再次尝试安装。。
然而并没有什么卵用，似乎只要一按全量更新，网站直接歇菜。后台密码也直接恢复默认。
最让我意外的是，SSH链接服务器进行更新则完全没有问题，但后台密码仍会被恢复默认。
所以，全量更新这个功能在现在来说真的不是一个定时炸弹么？

**Comment by abbeyokgo** [comment]
已修复
