### ISSUE TITLE
使用onedrive无法刷新出目录,请问可能是啥问题

### ISSUE THREAD

**Issue by wstvjx** [abbeyokgo/PyOne#58]
python /root/PyOne/function.py UpdateFile A
update A's file
[start] getting files from url https://graph.microsoft.com/v1.0/me/drive/root/children?expand=thumbnails
error:The caller does not have permission to perform the action.! waiting 180s
thread Thread-3's status True,qsize 1
[start] getting files from url https://graph.microsoft.com/v1.0/me/drive/root/children?expand=thumbnails
thread Thread-3's status True,qsize 0
error status times:2
error:The caller does not have permission to perform the action.! waiting 180s
thread Thread-3's status True,qsize 0
error status times:3
thread Thread-3's status True,qsize 0
error status times:4
thread Thread-3's status True,qsize 0
error status times:5
thread Thread-3's status True,qsize 0
error status times:6
thread Thread-3's status True,qsize 0
error status times:7
thread Thread-3's status True,qsize 0
error status times:8
thread Thread-3's status True,qsize 0
error status times:9
thread Thread-3's status True,qsize 0
error status times:10
thread Thread-3's status True,qsize 0
error status times:11
thread Thread-3's status True,qsize 0
error status times:12
thread Thread-3's status True,qsize 0
error status times:13
thread Thread-3's status True,qsize 0
error status times:14
thread Thread-3's status True,qsize 0
error status times:15
thread Thread-3's status True,qsize 0
error status times:16
thread Thread-3's status True,qsize 0
error status times:17
thread Thread-3's status True,qsize 0
error status times:18
thread Thread-3's status True,qsize 0
error status times:19
thread Thread-3's status True,qsize 0
error status times:20
force kill thread:Thread-3
A:/ all thread stop!
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 811, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 764, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/root/PyOne/app/utils/updatefile.py", line 61, in Dir
    RemoveRepeatFile()
  File "/root/PyOne/app/utils/header.py", line 200, in RemoveRepeatFile
    deleteData=mongo.db.items.aggregate([
AttributeError: 'NoneType' object has no attribute 'items'

all users update status is complete
update file success!
Killed

**Comment by abbeyokgo** [comment]
更新代码

**Comment by wstvjx** [comment]
谢谢大佬，自己还以为是onedrive账户的事弄了半天，更新秒解决。
