### ISSUE TITLE
在pyone文件夹下没有找到supervisord.conf

### ISSUE THREAD

**Issue by sdshdv** [abbeyokgo/PyOne#59]
只有supervisord.conf.sample  这样如何无损升级4.0?

**Comment by sdshdv** [comment]
折腾了半天,打算重新安装了,结果运行sh install.sh的时候又提示install.sh: 2: install.sh: Syntax error: "(" unexpected

**Comment by abbeyokgo** [comment]
**第一、你应该是用一键脚本安装的pyone**

**第二、你的系统应该也不是centos7**

**第三、如果需要升级4.0，建议你换到centos7再来升级，[通过宝塔安装MongoDB和redis](https://wiki.pyone.me/pyone-an-zhuang/an-zhuang-bao-ta-bao-ta-an-zhuang-cha-jian-bu-fen.html)，r然后按照这个步骤来升级：**

1. 备份config.py，并改名为self_config.py；

2. 备份data目录

3. 删除原来的PyOne目录

4. 重新git clone https://www.github.com/abbeyokgo/PyOne.git

5. 运行安装脚本：sh update.sh

6. 将self_config.py和data目录复制回去，其中备份的self_config.py替换掉刚新建的self_config.py

7. 创建一个锁定文件：touch .install

8. 运行网站：supervisord -c supervisord.conf
