### ISSUE TITLE
日志进程无法自动结束

### ISSUE THREAD

**Issue by Kamorj** [abbeyokgo/PyOne#69]
PyOne后台界面点击查看实时日志（多次点击会重复进程），后台进程只能手动kill。如果有大量实时日志，会导致CPU一直处于满载负荷状态。

>~$ ps -ef | grep PyOne
root     19175  3728  0 06:54 ?        00:00:00 tail -30f /root/PyOne/logs/PyOne.running.log
root     19183  3728  0 06:55 ?        00:00:00 tail -30f /root/PyOne/logs/PyOne.running.log
root     19211  3728  0 06:56 ?        00:00:00 tail -30f /root/PyOne/logs/PyOne.running.log
root     19333  3728  0 07:02 ?        00:00:00 tail -30f /root/PyOne/logs/PyOne.error.log
root     19336  3728  0 07:02 ?        00:00:00 tail -30f /root/PyOne/logs/PyOne.error.log

**Comment by abbeyokgo** [comment]
感谢。20190323已修复bug

**Comment by Kamorj** [comment]
更新之后点击运行日志，再点击其他界面，几秒后会导致404。
