### ISSUE TITLE
后台log界面报错

### ISSUE THREAD

**Issue by Zxilly** [abbeyokgo/PyOne#73]
route:/admin/logs 
exception: 
jq.js:69 
Uncaught DOMException: Failed to execute 'querySelectorAll' on 'Document': '/admin/logs?logname=running' is not a valid selector. at v (https://cdn.staticfile.org/mdui/0.4.2/js/mdui.min.js:6:1252) at HTMLAnchorElement. (https://cdn.staticfile.org/mdui/0.4.2/js/mdui.min.js:6:40081) at x (https://cdn.staticfile.org/mdui/0.4.2/js/mdui.min.js:6:2088) at c.each (https://cdn.staticfile.org/mdui/0.4.2/js/mdui.min.js:6:3192) at t._setActive (https://cdn.staticfile.org/mdui/0.4.2/js/mdui.min.js:6:39976) at new t (https://cdn.staticfile.org/mdui/0.4.2/js/mdui.min.js:6:39496) at HTMLDivElement. (https://cdn.staticfile.org/mdui/0.4.2/js/mdui.min.js:6:41598) at s (https://cdn.staticfile.org/mdui/0.4.2/js/mdui.min.js:6:20489) at HTMLDivElement. (https://cdn.staticfile.org/mdui/0.4.2/js/mdui.min.js:6:20780) at x (https://cdn.staticfile.org/mdui/0.4.2/js/mdui.min.js:6:2088) v @ jq.js:69 (anonymous) @ tab.js:149 x @ jq.js:178 each @ jq.js:345 t._setActive @ tab.js:129 t @ tab.js:73 (anonymous) @ tab.data.js:12 s @ mutation.js:42 (anonymous) @ mutation.js:71 x @ jq.js:178 each @ jq.js:345 r.mutation @ mutation.js:70 (anonymous) @ tab.data.js:8 (anonymous) @ jq.js:1545 logs?logname=error:1

**Comment by abbeyokgo** [comment]
js错误不用管
