### ISSUE TITLE
安装后文件目录显示不了

### ISSUE THREAD

**Issue by airectx** [abbeyokgo/PyOne#74]
新小鸡安装pyone，安装完绑定od全量更新后，打开网页没有刷新文件目录
![py](https://user-images.githubusercontent.com/13275988/55553034-ac66f580-5711-11e9-8f7c-353ff280e517.PNG)
![pyone](https://user-images.githubusercontent.com/13275988/55553045-b4269a00-5711-11e9-958b-2bfdf6e80de1.PNG)

**Comment by abbeyokgo** [comment]
看错误日志

**Comment by airectx** [comment]
[PyOne.error.log](https://github.com/abbeyokgo/PyOne/files/3051466/PyOne.error.log)
[PyOne.running.log](https://github.com/abbeyokgo/PyOne/files/3051467/PyOne.running.log)
环境：CentOS Linux release 7.6.1810 (Core)
python 2.7.16
mongodb 3.2.22
redis 5.0.4

**Comment by abbeyokgo** [comment]
看不出什么，再重新绑定试试

**Comment by airectx** [comment]
重新绑定也还是刷不出来，直接重装系统了，重装后跑起来了。。。
环境CentOS 7.6.1810，python2.7.5 mongodb3.6 redis3.2
