### ISSUE TITLE
无法正常解析MarkDown语法？

### ISSUE THREAD

**Issue by RikkaBlue** [abbeyokgo/PyOne#76]
无法正常显示MarkDown语法 "~~  ~~“ （删除格式）
~~就是这样~~
![](http://ww1.sinaimg.cn/large/005RlzD9ly1g28axqf90jj304f01bdgd.jpg)

**Comment by Boyuan26832** [comment]
README.md文件

**Comment by abbeyokgo** [comment]
下次更新确认一下

**Comment by Boyuan26832** [comment]
好的，谢谢

Abbey <notifications@github.com> 于 2019年4月29日周一 上午10:38写道：
