### ISSUE TITLE
后台设置 Redis 密码无效

### ISSUE THREAD

**Issue by hakula139** [abbeyokgo/PyOne#86]
Redis 已设置密码情况下，后台设置 Redis 密码字段无效，已重启过网站 / 服务器。self_config.py 对应字段经检查已修改，手动运行网站报错 ResponseError: NOAUTH Authentication required.；若 Redis 不设置密码，则可以正常使用。

使用 Redis 版本：5.0.5，MongoDB 版本：4.0.9，系统：Ubuntu 18.04，PyOne 版本：4.0

PyOne 使用 <https://wiki.pyone.me> 提供的一键脚本安装，除后台设置和 self_config.py 外未修改其他配置。

**Comment by abbeyokgo** [comment]
确认`self_config.py`的`REDIS_PASSWORD`是否正确

**Comment by hakula139** [comment]
确认正确。不过其中包含一些特殊字符，不知道是否会有影响。

**Comment by abbeyokgo** [comment]
方便的话QQ群找我，ssh调试一下

**Comment by Songkeys** [comment]
同样的问题

**Comment by Songkeys** [comment]
这里根本没有初始化密码呀……
https://github.com/abbeyokgo/PyOne/blob/01b4d13a965c4e06393205361d13034e1f0f8a66/run.py#L28

**Comment by abbeyokgo** [comment]
哦，那我知道了

**Comment by abbeyokgo** [comment]
修复了
