### ISSUE TITLE
问个问题

### ISSUE THREAD

**Issue by AlbertETA** [abbeyokgo/PyOne#9]
这个Issue不算是bug反馈，可是我没搞懂老哥你在后台设计的“缓存过期时间(秒)”有什么作用。。是为了自动更新文件吗？可是默认300秒过期后新增的文件依然没有更（出）新（现）呀，除非手动更新。

**Comment by abbeyokgo** [comment]
onedrive api获取的文件直链都是临时的，具有有效期，这里设置多久后重新获取文件直链
