### ISSUE TITLE
网盘管理异常

### ISSUE THREAD

**Issue by fxbjhc** [abbeyokgo/PyOne#93]
点击删除盘位后实际好像删除了，但是列表显示还是有。并且好像不具备编辑分享目录的功能

**Comment by moefir** [comment]
这应该是更新之后的问题吧，其实是报错了的，删除盘位的时候

**Comment by moefir** [comment]
en？我又重装了一遍，没有报错了，配置文件是成功删除了，但是网页后台还是会显示

**Comment by fxbjhc** [comment]
> 这应该是更新之后的问题吧，其实是报错了的，删除盘位的时候

可能是吧，我今天第一次用pyone。一开始我还以为我服务器问题 换个两个试了试 又重装了一次系统

**Comment by moefir** [comment]
> 
> 
> > 这应该是更新之后的问题吧，其实是报错了的，删除盘位的时候
> 
> 可能是吧，我今天第一次用pyone。一开始我还以为我服务器问题 换个两个试了试 又重装了一次系统

没，我用了一会儿了，今天更新之后就出各种问题了，还有一个就是后台的网站搬家一点，整个后台全部报错502

**Comment by fxbjhc** [comment]
更新后已解决
