### ISSUE TITLE
安装好之后不能离线下载

### ISSUE THREAD

**Issue by yfnok** [abbeyokgo/PyOne#98]
通过命令去下载之后发现报错
root@debian:~/.aria2# aria2c https://dldir1.qq.com/qqfile/qq/PCQQ9.1.3/25332/QQ9.1.3.25332.exe

06/23 11:32:20 [NOTICE] Downloading 5 item(s)

06/23 11:32:20 [ERROR] IPv4 RPC: failed to bind TCP port 6800
Exception: [SocketCore.cc:312] errorCode=1 Failed to bind a socket, cause: Address already in use

06/23 11:32:20 [ERROR] Exception caught
Exception: [DownloadEngineFactory.cc:219] errorCode=1 Failed to setup RPC server.
root@debian:~/.aria2#

aira2的配置文件是这样的：

#Setting
dir=/root/Download
dht-file-path=/root/.aria2/dht.dat
save-session-interval=15
force-save=false
log-level=error
input-file=/root/.aria2/aria2.session
save-session=/root/.aria2/aria2.session

# Advanced Options
disable-ipv6=true
file-allocation=none
max-download-result=35
max-download-limit=20M

# RPC Options
enable-rpc=true
rpc-secret=123456
rpc-allow-origin-all=true
rpc-listen-all=true
rpc-save-upload-metadata=true
rpc-secure=false
rpc-max-request-size=100M

# see --split option
continue=true
max-concurrent-downloads=10
max-overall-download-limit=0
max-overall-upload-limit=5
max-upload-limit=1

**Comment by abbeyokgo** [comment]
没有设置好aria2的token，后台-系统设置-aria2设置
